// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "PushGoAppleCoreTests",
    defaultLocalization: "en",
    platforms: [
        .macOS(.v14),
    ],
    products: [
        .library(
            name: "PushGoAppleCore",
            targets: ["PushGoAppleCore"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/groue/GRDB.swift.git", from: "7.6.0"),
    ],
    targets: [
        .target(
            name: "PushGoAppleCore",
            dependencies: [
                .product(name: "GRDB", package: "GRDB.swift"),
            ],
            path: "Shared",
            exclude: [
                "Services/ChannelSubscriptionSyncStore.swift",
                "Services/BadgeManager.swift",
                "Services/NotificationContentPreparer.swift",
                "Services/NotificationSoundPreviewPlayer.swift",
                "Services/NotificationServiceProcessor.swift",
                "Services/ProviderIngressCoordinator.swift",
                "Application/NotificationIngressController.swift",
                "Repositories/ChannelSubscriptionStore.swift",
                "Utilities/PushGoNotificationNames.swift",
                "UI/AppFormControls.swift",
                "UI/AutomationRuntime.swift",
                "UI/EntityScreens.swift",
                "UI/KeyboardDismiss.swift",
                "UI/LiquidGlassEffect.swift",
                "UI/MessageDetailViewModel.swift",
                "UI/MessageListViewModel.swift",
                "UI/MessageSearchViewModel.swift",
                "UI/NotificationSoundEditorView.swift",
                "UI/PlatformColor.swift",
                "UI/PendingLocalDeletionBar.swift",
                "UI/PushGoMarkdownView.swift",
                "UI/RemoteImageView.swift",
                "UI/RootView.swift",
                "UI/SettingsViewModel.swift",
                "UI/SystemIntegrationSettingsGroup.swift",
                "UI/ToastView.swift",
            ],
            sources: [
                "Application/AppNavigationState.swift",
                "Application/ChannelSubscriptionController.swift",
                "Application/ChannelSyncController.swift",
                "Application/DataPageVisibilityController.swift",
                "Application/FeedbackPresentationPolicy.swift",
                "Application/LocalStoreRecoveryController.swift",
                "Application/LocalStoreRecoveryState.swift",
                "Application/MainTab.swift",
                "Application/PendingLocalDeletionController.swift",
                "Application/ProviderRouteController.swift",
                "Application/NotificationOpenController.swift",
                "Models/AppError.swift",
                "Models/MessageFilter.swift",
                "Models/NotificationSoundSettings.swift",
                "Models/PushMessage.swift",
                "Models/PushMessageSummary.swift",
                "Models/ServerConfig.swift",
                "Models/SystemIntegrationSettings.swift",
                "Models/WatchLightModels.swift",
                "Repositories/LocalDataStore.swift",
                "Repositories/MessageSearchIndex.swift",
                "Repositories/SwiftDataModels.swift",
                "SystemIntegration/PushGoAccessibilitySummaryBuilder.swift",
                "SystemIntegration/PushGoAppEntities.swift",
                "SystemIntegration/PushGoAppEntityQueries.swift",
                "SystemIntegration/PushGoAppIntents.swift",
                "SystemIntegration/PushGoAppShortcuts.swift",
                "SystemIntegration/PushGoDeepLink.swift",
                "SystemIntegration/PushGoNotificationActionPolicy.swift",
                "SystemIntegration/PushGoMessageSummarySystemBridge.swift",
                "SystemIntegration/PushGoProjectionSummaryBuilder.swift",
                "SystemIntegration/PushGoSpotlightIndexer.swift",
                "SystemIntegration/PushGoSpotlightIdentifier.swift",
                "SystemIntegration/PushGoSystemEntityKind.swift",
                "SystemIntegration/PushGoSystemOpenTarget.swift",
                "SystemIntegration/PushGoSystemPrivacyPolicy.swift",
                "SystemIntegration/PushGoSystemRouter.swift",
                "SystemIntegration/PushGoSystemSummary.swift",
                "SystemIntegration/PushGoSystemSummaryBuilder.swift",
                "SystemIntegration/PushGoSystemIntentRouter.swift",
                "SystemIntegration/PushGoUserActivityBuilder.swift",
                "UI/EntityProjectionModels.swift",
                "Services/NotificationHandling.swift",
                "Services/NotificationIngressInbox.swift",
                "Services/NotificationSoundManager.swift",
                "Services/ProviderDeliveryAckFailureStore.swift",
                "Services/ChannelSubscriptionService.swift",
                "Services/MessageStateCoordinator.swift",
                "Services/PushRegistrationService.swift",
                "Utilities/AnyCodable.swift",
                "Utilities/AppConstants.swift",
                "Utilities/ChannelNameValidator.swift",
                "Utilities/ChannelPasswordValidator.swift",
                "Utilities/KeychainStore.swift",
                "Utilities/LocalizationManager.swift",
                "Utilities/LocalizationProvider.swift",
                "Utilities/ManualNotificationKeyValidator.swift",
                "Utilities/NotificationContextSnapshot.swift",
                "Utilities/NotificationPayloadSemantics.swift",
                "Utilities/NotificationSoundResolver.swift",
                "Utilities/NotificationSoundSharedState.swift",
                "Utilities/ProjectionSemantics.swift",
                "Utilities/PushGoMarkdownCore.swift",
                "Utilities/SharedImageCache.swift",
                "Utilities/PushRegistrationSemantics.swift",
                "Utilities/SearchQuerySemantics.swift",
                "Utilities/UserInfoSanitizer.swift",
                "Utilities/WatchLightQuantizer.swift",
            ],
            swiftSettings: [
                .unsafeFlags([
                    "-strict-concurrency=complete",
                    "-warnings-as-errors",
                ])
            ]
        ),
        .testTarget(
            name: "PushGoAppleCoreTests",
            dependencies: ["PushGoAppleCore"],
            path: "Tests/PushGoAppleCoreTests"
        ),
    ]
)
